version: 2.1
commands:
  install-binary:
    steps:
      - run: |
          export GITHUB_OAUTH_TOKEN=${GITHUB_API_TOKEN}
          echo $GITHUB_OAUTH_TOKEN
          wget https://github.com/gruntwork-io/fetch/releases/download/v0.4.5/fetch_linux_amd64
          ls -al



jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - install-binary

workflows:
  test_my_app:
    jobs:
      - build

