version: 2.1
commands:
  install-binary:
    steps:
      - run: |
          export GITHUB_OAUTH_TOKEN=${GITHUB_API_TOKEN}
          echo $GITHUB_OAUTH_TOKEN
          wget --version


jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - install-binary

workflows:
  test_my_app:
    jobs:
      - build

