version: 2.1
commands:
  install-binary:
    steps:
      - run: |
          export GITHUB_OAUTH_TOKEN=${GITHUB_API_TOKEN}
          echo $GITHUB_OAUTH_TOKEN
          wget https://github.com/gruntwork-io/fetch/releases/download/v0.4.5/fetch_linux_amd64
          chmod +x fetch_linux_amd64
          ./fetch_linux_amd64 -h
          ls -l
          pwd
          cd function
          ls -l
          cd -
          pwd                  




jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    working_directory: ~/project
    steps:
      - checkout
      - install-binary

workflows:
  test_my_app:
    jobs:
      - build

